import { ArrowLeft, ArrowRight, ArrowUp, Baby, Banknote, Bell, Bike, BriefcaseBusiness, BrushCleaning, Building2, Camera, Carrot, Check, ChefHat, ChevronDown, ChevronRight, CircleCheck, CircleDashed, ClipboardList, Clock, CodeXml, CreditCard, Croissant, CupSoda, FileText, Globe, Grid2X2, Headset, History, House, Image, Inbox, Info, LayoutDashboard, ListFilter, LocateFixed, LockKeyhole, LogOut, Mail, MapPin, Menu, MessageSquare, Milk, Minus, Monitor, Moon, Navigation, Package, PartyPopper, PawPrint, Pencil, Phone, Pill, Plug, Plus, Printer, ReceiptText, RefreshCw, Search, Settings, ShieldCheck, ShoppingBag, ShoppingBasket, ShoppingCart, SlidersHorizontal, Smartphone, SoapDispenserDroplet, Star, Store, Sun, Tag, Ticket, Trash2, TriangleAlert, Upload, UserRound, UsersRound, Wallet, Wifi, X } from 'lucide-react';
import type { LucideProps } from 'lucide-react';

const icons = {
  arrow: ArrowRight,
  back: ArrowLeft,
  chevron: ChevronRight,
  check: Check,
  box: Package,
  pin: MapPin,
  phone: Phone,
  route: Navigation,
  shop: Store,
  bell: Bell,
  history: History,
  help: Headset,
  user: UserRound,
  cash: Banknote,
  sun: Sun,
  moon: Moon,
  system: Monitor,
  lock: LockKeyhole,
  info: Info,
  close: X,
  warning: TriangleAlert,
  wifi: Wifi,
  search: Search,
  shield: ShieldCheck,
  logout: LogOut,
  location: LocateFixed,
  refresh: RefreshCw,
  camera: Camera,
  bike: Bike,
  file: FileText,
  message: MessageSquare,
  clock: Clock,
  globe: Globe,
  up: ArrowUp,
  home: House,
  basket: ShoppingBasket,
  grid: Grid2X2,
  receipt: ReceiptText,
  card: CreditCard,
  sliders: SlidersHorizontal,
  ticket: Ticket,
  plus: Plus,
  minus: Minus,
  filter: ListFilter,
  bag: ShoppingBag,
  star: Star,
  edit: Pencil,
  trash: Trash2,
  overview: LayoutDashboard,
  orders: ClipboardList,
  package: Package,
  rider: Bike,
  team: UsersRound,
  finance: Wallet,
  settings: Settings,
  monitor: Monitor,
  down: ChevronDown,
  right: ChevronRight,
  checkCircle: CircleCheck,
  code: CodeXml,
  support: Headset,
  menu: Menu,
  alert: TriangleAlert,
  store: Store,
  upload: Upload,
  empty: Inbox,
  tag: Tag,
  image: Image,
  chef: ChefHat,
  celebrate: PartyPopper,
  online: CircleCheck,
  offline: CircleDashed,
  printer: Printer,
  mail: Mail,
  smartphone: Smartphone,
  briefcase: BriefcaseBusiness,
  building: Building2,
  cart: ShoppingCart,
  carrot: Carrot,
  milk: Milk,
  drink: CupSoda,
  bakery: Croissant,
  pill: Pill,
  care: SoapDispenserDroplet,
  baby: Baby,
  household: BrushCleaning,
  plug: Plug,
  paw: PawPrint,
} as const;
export type ReferenceIconName = keyof typeof icons;
export interface ReferenceIconProps extends Omit<LucideProps, 'name' | 'size'> {
  name: ReferenceIconName;
  size?: 'normal' | 'sm' | 'lg';
  label?: string;
}
export function ReferenceIcon({ name, size = 'normal', className = '', label, ...props }: ReferenceIconProps) {
  const Glyph = icons[name];
  return <Glyph {...props} strokeWidth={props.strokeWidth ?? 2}
    className={`icon ${size === 'normal' ? '' : size} ${className}`.trim()}
    aria-hidden={label ? undefined : true} focusable="false"
    role={label ? 'img' : undefined} aria-label={label} />;
}
