"""Local browser-reference tests only. Never runs native app/API operations."""
from pathlib import Path
import json, os, shutil, argparse
from playwright.sync_api import sync_playwright
ROOT=Path(__file__).resolve().parents[1];REF=ROOT/'reference';results=[]
def record(name,ok,detail=None):
 results.append({'name':name,'pass':bool(ok),'detail':detail})
def run():
 parser=argparse.ArgumentParser(description=__doc__)
 parser.add_argument('--out',type=Path,default=Path('customer-preview-retest.json'))
 args=parser.parse_args()
 if args.out.resolve() == (ROOT/'QA_RESULTS.json').resolve() or (ROOT/'reference').resolve() in args.out.resolve().parents:
  parser.error('Retest output must not overwrite historical QA or locked reference files.')
 with sync_playwright() as p:
  exe=os.environ.get('CHROMIUM_PATH') or shutil.which('chromium') or shutil.which('google-chrome')
  b=p.chromium.launch(**({'executable_path':exe} if exe else {}))
  page=b.new_page(viewport={'width':390,'height':844},device_scale_factor=1)
  errors=[];requests=[]
  page.on('pageerror',lambda e:errors.append(str(e)))
  page.on('request',lambda r:requests.append(r.url))
  page.set_content((REF/'SirfBazar_Customer_Mobile.html').read_text(),wait_until='load')
  page.evaluate("document.documentElement.classList.add('capture')")
  scenes=json.loads((REF/'SCREENS.json').read_text())
  bad=[]
  for t in ['light','dark']:
   page.evaluate('(t)=>__customerDesign.theme(t)',t)
   for s in scenes:
    page.evaluate('(s)=>__customerDesign.scene(s)',s['key'])
    r=page.evaluate('''()=>({w:innerWidth,doc:document.documentElement.scrollWidth,content:document.querySelector('#scroller').scrollWidth, text:document.querySelector('#main-content').innerText.length})''')
    if r['doc']>r['w']+1 or r['content']>r['w']+1 or r['text']<10:bad.append([t,s['key'],r])
  record('All 42 scenes render in both themes without horizontal overflow',not bad,{'renders':84,'failures':bad})
  for w,h in [(320,740),(360,800),(412,915)]:
   page.set_viewport_size({'width':w,'height':h});issues=[]
   for s in scenes:
    page.evaluate('(s)=>__customerDesign.scene(s)',s['key'])
    r=page.evaluate('''()=>({w:innerWidth,d:document.documentElement.scrollWidth,s:document.querySelector('#scroller').scrollWidth})''')
    if max(r['d'],r['s'])>w+1:issues.append([s['key'],r])
   record(f'42 scenes at {w} logical width',not issues,issues)
  page.set_viewport_size({'width':390,'height':844})
  page.evaluate("__customerDesign.scene('home')")
  record('Guest entry has no authentication or modal',page.evaluate("!__customerDesign.getState().member && !__customerDesign.getState().modal"))
  page.locator('[data-act="add:milk"]').first.click()
  record('Adding does not request sign-in',page.evaluate("__customerDesign.getState().cart.milk===1&&!__customerDesign.getState().modal"))
  page.evaluate("__customerDesign.dispatch('add:banana');__customerDesign.dispatch('go:basket')")
  record('Second merchant does not clear first merchant',page.evaluate("__customerDesign.getState().cart.milk===1&&__customerDesign.getState().cart.banana===1"))
  page.evaluate("__customerDesign.dispatch('go:checkout');__customerDesign.dispatch('checkout-next')")
  record('Guest address validation precedes checkout sign-in',page.locator('#checkoutError').inner_text()!='' and page.evaluate('!__customerDesign.getState().modal'))
  page.locator('[data-field="fullAddress"]').fill('Example Street 12')
  page.locator('[data-field="city"]').fill('Lahore')
  page.locator('[data-field="name"]').fill('Example customer')
  page.evaluate("__customerDesign.dispatch('checkout-next')")
  record('Identity is requested only on deliberate checkout continuation',page.evaluate("__customerDesign.getState().modal==='signin'"))
  page.locator('[data-field="authPhone"]').fill('3000000000')
  page.evaluate("__customerDesign.theme('dark')")
  record('Theme switching preserves address and input',page.locator('[data-field="authPhone"]').input_value()=='3000000000' and page.evaluate("__customerDesign.getState().address.fullAddress==='Example Street 12'"))
  page.locator('[data-act="send-code"]').click()
  page.locator('[data-field="authCode"]').fill('654321')
  page.locator('[data-act="verify-code"]').click()
  record('Verification does not place an order',page.evaluate("__customerDesign.getState().view==='merge'&&__customerDesign.getState().member&&!__customerDesign.getState().orderPlaced"))
  record('Basket preserved after local verification',page.evaluate("__customerDesign.getState().cart.milk===1&&__customerDesign.getState().cart.banana===1"))
  page.evaluate("__customerDesign.dispatch('go:review')")
  record('Separate explicit Place order action exists',page.locator('[data-act="place"]').count()==1)
  page.locator('[data-act="place"]').click()
  record('Local completion snapshot agrees with selected basket',page.evaluate("__customerDesign.getState().orderSnapshot.total===61000 && Object.keys(__customerDesign.getState().cart).length===0"))
  # milk 290 + banana 180 + two deliveries 120 + service20 = 610
  record('Sent receipt does not imply merchant acceptance', 'awaiting confirmation' in page.locator('#main-content').inner_text().lower())
  page.evaluate("__customerDesign.scene('signin')")
  page.locator('.sheet [data-act="close"]').first.click()
  record('Dismissing sign-in keeps basket',page.evaluate("!__customerDesign.getState().modal&&__customerDesign.getState().cart.milk===1"))
  page.evaluate("__customerDesign.scene('verify')")
  page.locator('[data-act="verify-code"]').click()
  record('Invalid code has inline feedback',bool(page.locator('#authError').inner_text()))
  page.evaluate("__customerDesign.scene('catalog')")
  record('Global catalogue does not show a fake price or Add',page.locator('.add-btn').count()==0 and page.locator('.price').count()==0)
  page.evaluate("__customerDesign.scene('search')")
  page.locator('[data-field="search"]').fill('milk');page.wait_for_timeout(300)
  record('Product search filters local fixture',page.locator('.product-card').count()==1)
  page.evaluate("__customerDesign.scene('issue');__customerDesign.dispatch('send-issue')")
  record('Issue send validates meaningful fields',bool(page.locator('#issueError').inner_text()))
  page.evaluate("__customerDesign.scene('home');__customerDesign.dispatch('auth:account')")
  page.wait_for_timeout(30)
  page.keyboard.press('Tab');inside=page.evaluate("document.querySelector('#sheet').contains(document.activeElement)")
  for _ in range(15):page.keyboard.press('Tab');inside=inside and page.evaluate("document.querySelector('#sheet').contains(document.activeElement)")
  page.keyboard.press('Escape')
  record('Modal focus is contained and Escape closes without login',inside and page.evaluate('!__customerDesign.getState().modal&&!__customerDesign.getState().member'))
  page.evaluate("__customerDesign.scene('appearance');__customerDesign.theme('system')")
  page.emulate_media(color_scheme='dark');page.wait_for_timeout(60)
  t1=page.evaluate("document.documentElement.dataset.theme==='dark'")
  page.emulate_media(color_scheme='light');page.wait_for_timeout(60)
  record('System follows device preference',t1 and page.evaluate("document.documentElement.dataset.theme==='light'"))
  page.evaluate("__customerDesign.theme('dark')");page.emulate_media(color_scheme='light');page.wait_for_timeout(30)
  record('Explicit theme does not follow OS changes',page.evaluate("document.documentElement.dataset.theme==='dark'"))
  page.emulate_media(reduced_motion='reduce');page.evaluate("__customerDesign.scene('loading')")
  record('Reduced motion disables skeleton animation',page.locator('.shimmer').first.evaluate("e=>getComputedStyle(e).animationName")=='none')
  page.evaluate("__customerDesign.scene('uncertain')")
  record('Uncertain order cannot be replayed through a Place button',page.locator('[data-act=place]').count()==0 and page.locator('[data-act=check-order]').count()==1)
  page.evaluate("__customerDesign.scene('payment')")
  record('No payment-confirm action is exposed',page.locator('[data-act*=confirm-payment]').count()==0)
  record('No JavaScript exceptions',not errors,errors)
  record('No network requests in preview',not requests,requests)
  b.close()
 out={'scope':'local HTML design only; not native, hosted persistence or live API tests','results':results,'passed':sum(x['pass'] for x in results),'total':len(results)}
 args.out.parent.mkdir(parents=True,exist_ok=True)
 args.out.write_text(json.dumps(out,indent=2))
 print(json.dumps(out,indent=2))
 if out['passed']!=out['total']:raise SystemExit(1)
if __name__=='__main__':run()
