// Load with playwright-cli run-code --filename after opening the LOCAL website.
// All API responses/mutations are intercepted. Never run against a live origin.
async (page) => {
  const origin = new URL(page.url()).origin;
  if (!['127.0.0.1', 'localhost'].includes(new URL(origin).hostname)) throw Error('Hero fixtures require a local preview.');
  const checks = [];
  await page.unroute('**/_next/image?*');
  const check = (condition, label) => { if (!condition) throw Error(label); checks.push(label); };
  const requests = [];
  let mode = 'success';
  let count = 0;
  const merchant = { id: 'fixture-shop', shopName: 'Local test shop', city: 'Lahore', isOnline: true, isOpen: true, minimumOrderValuePaisa: 0 };
  const product = { productId: 'fixture-product', merchantProductId: 'fixture-offer', name: 'Test milk', size: '1 L', pricePaisa: 32000, stockQuantity: 10, imageUrl: '/design/product-milk.svg', merchant };
  const categories = [{id:'dairy',slug:'milk-eggs-bread',name:'Milk, Eggs & Bread',children:[{id:'milk',slug:'milk',name:'Milk'}]}];
  const cart = () => ({ id:'fixture-cart', itemCount:count, groups:count ? [{merchant,deliveryFeePaisa:0,subtotalPaisa:count*32000,items:[{id:'fixture-item',merchantProductId:'fixture-offer',productId:'fixture-product',name:'Test milk',imageUrl:'/design/product-milk.svg',quantity:count,unitPricePaisa:32000,totalPaisa:count*32000,inStock:true,stockQuantity:10}]}] : [], subtotalPaisa:count*32000,deliveryFeePaisa:0,serviceFeePaisa:0,totalPaisa:count*32000 });
  await page.route('**/api/**', async route => {
    const request = route.request(); const url = new URL(request.url());
    const path = url.pathname.replace(/^\/api/, '');
    requests.push({method:request.method(),path,query:url.search});
    let body = {};
    const headers = {'access-control-allow-origin':origin,'access-control-allow-headers':'content-type,x-guest-session,authorization','access-control-allow-methods':'GET,POST,PUT,OPTIONS'};
    if(request.method() === 'OPTIONS') return route.fulfill({status:204,headers});
    if(mode === 'loading' && path.startsWith('/products/nearby')) await new Promise(resolve => setTimeout(resolve, 1200));
    if((mode === 'error' && /products\/nearby|merchants\/nearby/.test(path)) || (mode === 'productError' && path.startsWith('/products/nearby'))) return route.fulfill({status:503,headers,json:{message:'Unavailable'}});
    if(path === '/products/categories') body = mode === 'empty' ? [] : categories;
    else if(path === '/merchants/nearby') body = {items:mode === 'empty' ? [] : [merchant],total:mode === 'empty' ? 0 : 1};
    else if(path === '/products/nearby' || path === '/products/search') body = {items:mode === 'empty' ? [] : [product],total:mode === 'empty' ? 0 : 1};
    else if(path === '/guest/session') body = {sessionToken:'fixture-guest'};
    else if(path === '/guest/cart/items' && request.method() === 'POST') { count += request.postDataJSON().quantity; body = cart(); }
    else if(path.startsWith('/guest/cart/items/') && request.method() === 'PUT') { count = request.postDataJSON().quantity; body = cart(); }
    else if(path === '/guest/cart') body = cart();
    else body = [];
    return route.fulfill({headers,json:body});
  });
  await page.evaluate(() => localStorage.clear());
  await page.goto(origin);
  await page.getByRole('heading',{name:'Everyday groceries from local shops.'}).waitFor();
  await page.getByRole('button',{name:'Set delivery location'}).waitFor();
  check(await page.getByRole('button',{name:'Add Test milk to basket'}).count() === 0, 'Nearby products remain hidden until a delivery location is confirmed');
  check(await page.getByRole('dialog').count() === 0, 'Home opens without a forced login or location prompt');
  check(await page.evaluate(() => !localStorage.getItem('sb.guestToken')), 'Home browsing does not create a guest session');
  await page.setViewportSize({width:1672,height:941});
  await page.screenshot({path:'output/playwright/grocery-hero-unconfirmed.png'});
  await page.context().grantPermissions(['geolocation'], {origin});
  await page.context().setGeolocation({latitude:31.40981,longitude:74.28032,accuracy:10});
  await page.getByRole('button',{name:'Set delivery location'}).click();
  await page.getByRole('button',{name:'Use my current location',exact:true}).click();
  await page.getByRole('button',{name:'Confirm this location',exact:true}).click();
  await page.getByRole('dialog').waitFor({state:'hidden'});
  await page.getByRole('heading',{name:'Everyday groceries from shops near you.'}).waitFor();
  const saved = await page.evaluate(() => JSON.parse(localStorage.getItem('sb.location')));
  check(saved.latitude === 31.40981 && saved.longitude === 74.28032, 'Real location picker saves selected GPS coordinates');
  await page.getByRole('button',{name:'Add Test milk to basket'}).click();
  await page.getByRole('group',{name:'Test milk quantity'}).waitFor();
  await page.getByLabel('1 in basket').waitFor();
  await page.getByRole('button',{name:'Increase Test milk quantity'}).click();
  await page.getByLabel('2 in basket').waitFor();
  await page.getByRole('button',{name:'Decrease Test milk quantity'}).click();
  await page.getByLabel('1 in basket').waitFor();
  await page.getByRole('link',{name:'Basket with 1 items'}).waitFor();
  check(await page.evaluate(() => !localStorage.getItem('sb.accessToken')), 'Guest quantity controls update the real basket without signing in');
  await page.getByRole('link',{name:'Shop groceries',exact:true}).click();
  await page.waitForURL('**/search');
  await page.getByRole('heading',{name:'Find your everyday essentials'}).waitFor();
  check(await page.evaluate(() => JSON.parse(localStorage.getItem('sb.location')).latitude === 31.40981 && localStorage.getItem('sb.guestToken') === 'fixture-guest'), 'Product CTA preserves selected area and guest basket');
  await page.goto(origin);
  await page.getByRole('link',{name:'Explore local shops',exact:true}).click();
  await page.waitForURL('**/search?type=shops');
  await page.getByRole('heading',{name:'Your neighbourhood shops'}).waitFor();
  check(await page.getByRole('dialog').count() === 0, 'Shop CTA reaches guest discovery without auth');
  await page.goto(origin);
  const search = page.getByRole('textbox',{name:'Search products and shops'});
  await search.fill('milk'); await search.press('Enter');
  await page.waitForURL('**/search?q=milk');
  check(true,'Existing header search keeps its query');
  await page.getByRole('link',{name:'Dairy & eggs',exact:true}).click();
  await page.waitForURL('**/search?category=milk-eggs-bread');
  await page.getByRole('navigation',{name:'Subsections of Milk, Eggs & Bread'}).waitFor();
  check(true,'Header category opens real category/subsection browsing');
  await page.getByLabel('Account: sign up or sign in',{exact:true}).click();
  await page.getByRole('link',{name:'Sign up or sign in',exact:true}).waitFor();
  check(true,'Existing account sign-in/sign-up disclosure is available');
  await page.goto(origin);
  await page.getByRole('link',{name:'Basket with 1 items'}).click();
  await page.waitForURL('**/cart');
  await page.getByRole('heading',{name:'Your basket',exact:true}).waitFor();
  check(await page.getByRole('button',{name:/Continue to checkout/}).isVisible(), 'Guest basket retains checkout entry; no order placed');
  await page.goto(origin);
  await page.getByRole('link',{name:'Orders',exact:true}).click();
  await page.waitForURL('**/orders');
  check(true,'Orders navigation is unchanged');
  await page.goto(origin);
  await page.getByRole('heading',{name:/Everyday groceries/}).waitFor();
  await page.evaluate(() => document.fonts.ready);
  const captures=[];
  for(const theme of ['light','dark']) {
    await page.evaluate(theme => { localStorage.setItem('sb.theme',theme); window.dispatchEvent(new Event('sb:theme')); },theme);
    for(const width of [1672,1440,1366,1024,768,390,360,320]) {
      await page.setViewportSize({width,height:width>767 ? 941 : 844});
      await page.screenshot({path:`output/playwright/grocery-hero-${theme}-${width}.png`,fullPage:width<768});
      const measured = await page.evaluate(() => {
        const title=document.getElementById('home-hero-title'); const hero=title.closest('section'); const img=hero.querySelector('img');
        const box=hero.getBoundingClientRect(); const image=img.getBoundingClientRect();
        const c=getComputedStyle(title); const d=getComputedStyle(hero.querySelectorAll('p')[1]);
        const primary=getComputedStyle(hero.querySelector('a')); const secondary=getComputedStyle(hero.querySelectorAll('a')[1]);
        const linear = color => color.match(/[\d.]+/g).slice(0,3).map(Number).map(v=>v/255).map(v=>v<=.04045?v/12.92:((v+.055)/1.055)**2.4);
        const luminance = color => linear(color).reduce((sum,v,i)=>sum+v*[.2126,.7152,.0722][i],0);
        const contrast = (a,b) => {const x=luminance(a),y=luminance(b);return (Math.max(x,y)+.05)/(Math.min(x,y)+.05);};
        const background=getComputedStyle(hero).backgroundColor;
        return {width:innerWidth,overflow:document.documentElement.scrollWidth>innerWidth,hero:{width:box.width,height:box.height},image:{width:image.width,height:image.height},font:c.fontFamily,fontLoaded:document.fonts.check('800 56px "Plus Jakarta Sans"'),fontSize:c.fontSize,foreground:c.color,background,muted:d.color,ratios:{heading:contrast(c.color,background),description:contrast(d.color,background),primary:contrast(primary.color,primary.backgroundColor),secondary:contrast(secondary.color,background)},dpr:devicePixelRatio,scale:visualViewport.scale};
      });
      check(!measured.overflow, `${theme} ${width}px has no horizontal page overflow`);
      check(measured.background === (theme === 'dark' ? 'rgb(25, 34, 30)' : 'rgb(238, 247, 240)'), `${theme} ${width}px hero follows the selected appearance`);
      check(Object.values(measured.ratios).every(ratio=>ratio>=4.5), `${theme} ${width}px hero text and both CTAs meet AA contrast`);
      check(Math.abs(measured.image.width/measured.image.height-809/644)<.01,`${theme} ${width}px keeps complete artwork aspect ratio`);
      captures.push({theme,...measured});
    }
  }
  await page.setViewportSize({width:1672,height:941});
  await page.emulateMedia({colorScheme:'dark'});
  await page.evaluate(() => new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve))));
  await page.evaluate(() => {localStorage.setItem('sb.theme','system');window.dispatchEvent(new Event('sb:theme'));});
  check(await page.evaluate(() => document.documentElement.dataset.theme==='dark'), 'System follows dark OS preference');
  check(await page.locator('section[aria-labelledby="home-hero-title"]').evaluate(el=>getComputedStyle(el).backgroundColor==='rgb(25, 34, 30)'), 'System dark also changes the hero surface');
  await page.emulateMedia({colorScheme:'light'});
  await page.evaluate(() => new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve))));
  await page.waitForFunction(() => document.documentElement.dataset.theme === 'light');
  check(await page.evaluate(() => document.documentElement.dataset.theme==='light'), 'System reacts to light OS preference');
  check(await page.locator('section[aria-labelledby="home-hero-title"]').evaluate(el=>getComputedStyle(el).backgroundColor==='rgb(238, 247, 240)'), 'System light restores the original hero surface');
  const themeButton = page.getByRole('button',{name:'Appearance: system. Change appearance'});
  await themeButton.click(); await page.getByRole('button',{name:'Appearance: light. Change appearance'}).click();
  check(await page.evaluate(() => document.documentElement.dataset.theme==='dark' && JSON.parse(localStorage.getItem('sb.location')).latitude===31.40981), 'Visible appearance control cycles without resetting area');
  await page.getByRole('link',{name:'Basket with 1 items'}).waitFor();
  await page.emulateMedia({reducedMotion:'reduce'});
  await page.getByRole('link',{name:'Shop groceries',exact:true}).focus();
  const focus=await page.getByRole('link',{name:'Shop groceries',exact:true}).evaluate(el => ({outline:getComputedStyle(el).outlineWidth,transition:getComputedStyle(el).transitionDuration}));
  check(parseFloat(focus.outline)>=2 && focus.transition==='0s','Hero keyboard focus remains visible; reduced-motion disables transitions');
  await page.keyboard.press('Tab');
  check(await page.getByRole('link',{name:'Explore local shops',exact:true}).evaluate(el=>el===document.activeElement),'Keyboard order runs primary then secondary CTA');
  await page.screenshot({path:'output/playwright/grocery-hero-focus.png'});
  await page.setViewportSize({width:320,height:844});
  await page.evaluate(()=>document.documentElement.style.fontSize='200%');
  check(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'320px with 200% text does not overflow');
  await page.screenshot({path:'output/playwright/grocery-hero-text-200.png',fullPage:true});
  await page.evaluate(()=>document.documentElement.style.fontSize='');
  // Reflow at 200% browser zoom is modelled by halving a 1440px CSS viewport.
  await page.setViewportSize({width:720,height:470});
  check(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'200% zoom-equivalent 720px reflow does not overflow');
  await page.screenshot({path:'output/playwright/grocery-hero-zoom-reflow.png',fullPage:true});
  await page.setViewportSize({width:1672,height:941});
  mode='empty'; await page.reload();
  await page.getByRole('heading',{name:'No shops deliver to this area yet'}).waitFor();
  check(await page.getByRole('button',{name:'Change delivery location'}).isVisible(),'Empty coverage allows choosing another delivery location');
  await page.screenshot({path:'output/playwright/grocery-hero-empty.png'});
  mode='error'; await page.reload();
  await page.getByRole('button',{name:'Try again',exact:true}).waitFor();
  check(await page.getByRole('heading',{name:'No shops deliver to this area yet'}).count()===0,'API failure is not presented as empty coverage');
  await page.screenshot({path:'output/playwright/grocery-hero-error.png'});
  mode='productError'; await page.reload();
  await page.getByText('Local test shop',{exact:true}).waitFor();
  await page.getByText('We couldn’t load products for this delivery area.',{exact:true}).waitFor();
  check(await page.getByText('Local test shop',{exact:true}).isVisible(),'A product-feed failure does not hide successful nearby shops');
  await page.screenshot({path:'output/playwright/grocery-hero-product-error.png'});
  mode='loading'; await page.reload();
  await page.getByLabel('Loading products').waitFor();
  await page.screenshot({path:'output/playwright/grocery-hero-loading.png'});
  mode='success';
  await page.route('**/_next/image?*',route=>route.abort());
  await page.reload();
  await page.getByRole('link',{name:'Shop groceries',exact:true}).waitFor();
  check(await page.getByRole('link',{name:'Shop groceries',exact:true}).isVisible(),'Missing artwork leaves shopping CTA usable');
  await page.screenshot({path:'output/playwright/grocery-hero-image-failure.png'});
  check(requests.every(r=>r.method==='GET'||r.method==='OPTIONS'||(r.method==='POST' && ['/guest/session','/guest/cart/items'].includes(r.path))),'Only mocked guest-cart mutations used; no OTP/order/inventory calls');
  await page.evaluate(report => {window.__groceryHeroVerification = report;}, {checks,captures,focus,requestCount:requests.length});

}
